"""End-to-end sweep oracle: reproduce real MACS+ desktop reports.

The reports under ``fixtures/macs_reference_pdfs/<unit>/`` are Atlantic Park
Phase 2 parametric fire-load / glazing sweeps generated by MACS+ itself — Unit 6
(8 runs, mesh axis 40 mm) and a spread sampled from the Unit 7 sweep (12 runs,
mesh axis 52 mm), spanning fire loads ~109–1246 MJ/m² and including a failing
run (uf_max > 1). Every engine input is reconstructed straight from each PDF by
``macs_automation.pdf_oracle`` — no ``.frc`` needed — then replayed through the
FRACOF engine and checked against the PDF's own results.

The parser is covered without COM by ``test_pdf_oracle_parser.py``; this file
adds the engine half and is skipped with a clear reason when COM / Data.xml are
unavailable. On a MACS+ box run with:  pytest -m e2e -v
"""

from pathlib import Path

import pytest

from macs_automation.pdf_oracle import parse_pdf
from macs_automation.tests.conftest import com_and_data_available

REF_DIR = Path(__file__).parent / "fixtures" / "macs_reference_pdfs"
PDFS = sorted(REF_DIR.glob("*/run*.pdf"))


def _run_id(pdf: Path) -> str:
    return f"{pdf.parent.name}-{pdf.stem[:8]}"


@pytest.mark.e2e
@pytest.mark.com
class TestMacsSweepOracle:
    @pytest.fixture(scope="class")
    def sections_db(self):
        from macs_automation.data_loader import DEFAULT_DATA_PATH, load_data

        ok, reason = com_and_data_available()
        if not ok:
            pytest.skip(reason)
        return load_data(DEFAULT_DATA_PATH)["sections"]

    def _run(self, params, sections_db):
        from macs_automation.engine import MACSEngine

        eng = MACSEngine()
        eng.set_inputs(params, sections_db)
        return eng.run(method="parametric")

    @pytest.mark.parametrize("pdf", PDFS, ids=_run_id)
    def test_engine_reproduces_macs_report(self, pdf, sections_db):
        parsed = parse_pdf(pdf)
        out = self._run(parsed["params"], sections_db)
        oracle = parsed["oracle"]

        assert out["uf_max"] == pytest.approx(oracle["uf_max"], abs=0.005)
        assert out["factored_hot"] == pytest.approx(oracle["factored_hot"], abs=0.01)

        for side, ref in oracle["sides"].items():
            got = round(out[f"side_{side}_critical_temp"])
            assert got == pytest.approx(ref["critical_temp"], abs=2), (
                f"{_run_id(pdf)} side {side}: engine {got} vs PDF {ref['critical_temp']}"
            )
