"""Tests for frc_parser module — parses MACS+ .frc project files."""

from pathlib import Path
from urllib.parse import quote as urlquote

import pytest

from macs_automation.frc_parser import parse_frc, parse_frc_string


# Minimal .frc XML for testing
SAMPLE_FRC = """\
<?xml version="1.0" encoding="utf-8"?>
<!-- User Job File -->
<!-- Generated by MACS+ version 3.0.4 -->
<Root>
    <Signature>FRACOFJobFile</Signature>
    <FormatVersion>4.0</FormatVersion>
    <Generator>MACS+ version 3.0.4</Generator>
    <Date>13 January 2026, 17:17</Date>
    <Owner />
    <Country>EN</Country>
    <Environment>
        <Property Name="AppVersion" Value="3.0.4" />
    </Environment>
    <Input>
        <Project>
            <Property Name="CalculationBy" Value="Diana%20Prostire" />
            <Property Name="ClientName" Value="Winvic" />
            <Property Name="Comments" Value="First%20Floor%20Slab%20%28Office" />
            <Property Name="JobNumber" Value="0596" />
            <Property Name="ProjectName" Value="Sawley%20Interchange" />
        </Project>
        <GA>
            <Property Name="numbeam" Value="2" />
            <Property Name="span1" Value="11.2" />
            <Property Name="span2" Value="9.2" />
        </GA>
        <Deck>
            <Property Name="DeckId" Value="T10" />
            <Property Name="DeckName" Value="Metflor%2060" />
            <Property Name="SteelDeck" Value="1" />
            <Property Name="deck_bot" Value="125" />
            <Property Name="deck_depth" Value="60" />
            <Property Name="deck_stiff_height" Value="15" />
            <Property Name="deck_top" Value="144.8" />
            <Property Name="deck_trug" Value="300" />
            <Property Name="deck_type" Value="T" />
        </Deck>
        <Slab>
            <Property Name="conc_type" Value="NW" />
            <Property Name="conc_lambda" Value="1" />
            <Property Name="fck" Value="30" />
            <Property Name="slab_depth" Value="150" />
            <Property Name="mesh_type" Value="A193" />
            <Property Name="mesh_area_max" Value="193" />
            <Property Name="mesh_area_min" Value="193" />
            <Property Name="mesh_axis" Value="40" />
            <Property Name="mesh_strength" Value="500" />
            <Property Name="max_mesh_dia" Value="7" />
            <Property Name="min_mesh_dia" Value="7" />
        </Slab>
        <Beams>
            <Property Name="SideASecSize" Value="UB_457x152x60" />
            <Property Name="fy1" Value="355" />
            <Property Name="SideAEdgeFlag" Value="0" />
            <Property Name="SideACompoFlag" Value="1" />
            <Property Name="SideAsh_con" Value="80" />
            <Property Name="SideBSecSize" Value="UB_533x210x101" />
            <Property Name="fy2" Value="355" />
            <Property Name="SideBEdgeFlag" Value="1" />
            <Property Name="SideBCompoFlag" Value="0" />
            <Property Name="SideBsh_con" Value="80" />
            <Property Name="SideCSecSize" Value="UB_457x152x60" />
            <Property Name="fy3" Value="355" />
            <Property Name="SideCEdgeFlag" Value="0" />
            <Property Name="SideCCompoFlag" Value="1" />
            <Property Name="SideCsh_con" Value="80" />
            <Property Name="SideDSecSize" Value="UB_610x229x101" />
            <Property Name="fy4" Value="355" />
            <Property Name="SideDEdgeFlag" Value="1" />
            <Property Name="SideDCompoFlag" Value="0" />
            <Property Name="SideDsh_con" Value="80" />
            <Property Name="uSecSize" Value="UB_457x152x60" />
            <Property Name="fy5" Value="355" />
            <Property Name="ush_con" Value="80" />
            <Property Name="USecTypeFlag" Value="1" />
            <Property Name="uSec1Size" Value="UB_305x165x40" />
            <Property Name="uSec1Depth" Value="250" />
            <Property Name="uSec2Size" Value="UB_305x165x40" />
            <Property Name="uSec2Depth" Value="250" />
            <Property Name="uSecDiam" Value="200" />
        </Beams>
        <Loading>
            <Property Name="calc_slab_weight" Value="1" />
            <Property Name="cold_perm" Value="2" />
            <Property Name="lead_var_act" Value="5" />
            <Property Name="lead_var_fac" Value="0.5" />
            <Property Name="othr_var_act" Value="0" />
            <Property Name="othr_var_fac" Value="0.3" />
            <Property Name="slab_weight" Value="2.83" />
        </Loading>
        <Fire>
            <Property Name="Bc" Value="12" />
            <Property Name="Bfac" Value="1400" />
            <Property Name="Hc" Value="3.6" />
            <Property Name="Hw" Value="3.6" />
            <Property Name="Lc" Value="63" />
            <Property Name="Lw" Value="63" />
            <Property Name="Method" Value="1" />
            <Property Name="combustion_factor" Value="0.8" />
            <Property Name="growth_rate" Value="1" />
            <Property Name="qf" Value="511" />
            <Property Name="time_limit" Value="120" />
            <Property Name="window_percent" Value="95" />
        </Fire>
    </Input>
</Root>
"""


@pytest.fixture
def sample_frc_file(tmp_path):
    frc_file = tmp_path / "SawleyFF 1.frc"
    frc_file.write_text(SAMPLE_FRC, encoding="utf-8")
    return frc_file


class TestParseFrc:
    """Test parsing .frc files into internal parameter dicts."""

    def test_returns_params_and_project(self, sample_frc_file):
        result = parse_frc(sample_frc_file)
        assert "params" in result
        assert "project" in result

    def test_project_metadata(self, sample_frc_file):
        result = parse_frc(sample_frc_file)
        proj = result["project"]
        assert proj["ProjectName"] == "Sawley Interchange"
        assert proj["ClientName"] == "Winvic"
        assert proj["JobNumber"] == "0596"
        assert proj["CalculationBy"] == "Diana Prostire"
        # URL-decoded comments
        assert "First Floor Slab" in proj["Comments"]

    def test_geometry(self, sample_frc_file):
        params = parse_frc(sample_frc_file)["params"]
        assert params["span1"] == 11.2
        assert params["span2"] == 9.2
        assert params["numbeam"] == 2

    def test_deck(self, sample_frc_file):
        params = parse_frc(sample_frc_file)["params"]
        assert params["DeckId"] == "T10"
        assert params["deck_type"] == "T"
        assert params["deck_depth"] == 60.0
        assert params["deck_trug"] == 300.0
        assert params["deck_top"] == 144.8
        assert params["deck_bot"] == 125.0
        assert params["deck_stiff_height"] == 15.0

    def test_slab(self, sample_frc_file):
        params = parse_frc(sample_frc_file)["params"]
        assert params["conc_type"] == "NW"
        assert params["fck"] == 30.0
        assert params["slab_depth"] == 150.0
        assert params["mesh_type"] == "A193"
        assert params["mesh_area_max"] == 193.0
        assert params["mesh_area_min"] == 193.0
        assert params["mesh_axis"] == 40.0
        assert params["mesh_strength"] == 500.0

    def test_beams_unprotected(self, sample_frc_file):
        params = parse_frc(sample_frc_file)["params"]
        assert params["uSecSize"] == "UB_457x152x60"
        assert params["fy5"] == "355"
        assert params["ush_con"] == 80.0

    def test_beams_side_a(self, sample_frc_file):
        params = parse_frc(sample_frc_file)["params"]
        assert params["SideASecSize"] == "UB_457x152x60"
        assert params["fy1"] == "355"
        assert params["SideAEdgeFlag"] == 0
        assert params["SideACompoFlag"] == 1
        assert params["SideAsh_con"] == 80.0

    def test_beams_side_b_edge(self, sample_frc_file):
        params = parse_frc(sample_frc_file)["params"]
        assert params["SideBSecSize"] == "UB_533x210x101"
        assert params["SideBEdgeFlag"] == 1
        assert params["SideBCompoFlag"] == 0

    def test_beams_side_d(self, sample_frc_file):
        params = parse_frc(sample_frc_file)["params"]
        assert params["SideDSecSize"] == "UB_610x229x101"
        assert params["SideDEdgeFlag"] == 1
        assert params["SideDCompoFlag"] == 0

    def test_loading(self, sample_frc_file):
        params = parse_frc(sample_frc_file)["params"]
        assert params["lead_var_act"] == 5.0
        assert params["othr_var_act"] == 0.0
        assert params["cold_perm"] == 2.0
        assert params["lead_var_fac"] == 0.5
        assert params["othr_var_fac"] == 0.3
        assert params["slab_weight"] == 2.83

    def test_fire_method_parametric(self, sample_frc_file):
        """Method=1 in FRC should map to 'parametric'."""
        params = parse_frc(sample_frc_file)["params"]
        assert params["method"] == "parametric"

    def test_fire_compartment(self, sample_frc_file):
        params = parse_frc(sample_frc_file)["params"]
        assert params["Lc"] == 63.0
        assert params["Bc"] == 12.0
        assert params["Hc"] == 3.6
        assert params["Hw"] == 3.6
        assert params["Lw"] == 63.0
        assert params["window_percent"] == 95.0
        assert params["qf"] == 511.0
        assert params["Bfac"] == 1400.0
        assert params["combustion_factor"] == 0.8
        assert params["growth_rate"] == 1.0

    def test_fire_time_limit(self, sample_frc_file):
        params = parse_frc(sample_frc_file)["params"]
        assert params["time_limit"] == 120.0


class TestFireMethodMapping:
    """Test the FRC Method integer → internal method string mapping."""

    def _make_frc_with_method(self, method_val, tmp_path):
        xml = SAMPLE_FRC.replace(
            'Name="Method" Value="1"',
            f'Name="Method" Value="{method_val}"',
        )
        frc_file = tmp_path / "test.frc"
        frc_file.write_text(xml, encoding="utf-8")
        return frc_file

    def test_method_0_is_iso(self, tmp_path):
        frc = self._make_frc_with_method(0, tmp_path)
        params = parse_frc(frc)["params"]
        assert params["method"] == "iso"

    def test_method_1_is_parametric(self, tmp_path):
        frc = self._make_frc_with_method(1, tmp_path)
        params = parse_frc(frc)["params"]
        assert params["method"] == "parametric"

    def test_method_2_is_udf(self, tmp_path):
        frc = self._make_frc_with_method(2, tmp_path)
        params = parse_frc(frc)["params"]
        assert params["method"] == "udf"


class TestParseFrcString:
    """Test parsing from a string (for API upload use case)."""

    def test_parse_from_string(self):
        result = parse_frc_string(SAMPLE_FRC)
        assert result["params"]["span1"] == 11.2
        assert result["project"]["ProjectName"] == "Sawley Interchange"


class TestUrlDecoding:
    """Test that URL-encoded values are properly decoded."""

    def _make_frc_with_project_name(self, encoded_name, tmp_path):
        xml = SAMPLE_FRC.replace(
            'Name="ProjectName" Value="Sawley%20Interchange"',
            f'Name="ProjectName" Value="{encoded_name}"',
        )
        frc_file = tmp_path / "test.frc"
        frc_file.write_text(xml, encoding="utf-8")
        return frc_file

    def test_decodes_percent_encoded_spaces(self, tmp_path):
        frc = self._make_frc_with_project_name("Test%20Project%20Name", tmp_path)
        result = parse_frc(frc)
        assert result["project"]["ProjectName"] == "Test Project Name"

    def test_decodes_special_chars(self, tmp_path):
        frc = self._make_frc_with_project_name("Block%20A%2FB", tmp_path)
        result = parse_frc(frc)
        assert result["project"]["ProjectName"] == "Block A/B"


class TestInvalidFrcFile:
    """Test error handling for invalid files."""

    def test_not_xml(self, tmp_path):
        frc_file = tmp_path / "bad.frc"
        frc_file.write_text("this is not xml", encoding="utf-8")
        with pytest.raises(Exception):
            parse_frc(frc_file)

    def test_wrong_signature(self, tmp_path):
        xml = SAMPLE_FRC.replace("FRACOFJobFile", "SomethingElse")
        frc_file = tmp_path / "wrong.frc"
        frc_file.write_text(xml, encoding="utf-8")
        with pytest.raises(ValueError, match="signature"):
            parse_frc(frc_file)

    def test_missing_input_section(self, tmp_path):
        xml = '<?xml version="1.0"?><Root><Signature>FRACOFJobFile</Signature></Root>'
        frc_file = tmp_path / "noinput.frc"
        frc_file.write_text(xml, encoding="utf-8")
        with pytest.raises(ValueError, match="Input"):
            parse_frc(frc_file)


class TestRealFrcFile:
    """Tests against the actual .frc file in Downloads."""

    @pytest.fixture
    def real_frc_path(self):
        path = Path(r"C:\Users\IanShaw\Downloads\SawleyFF 1.frc")
        if not path.exists():
            pytest.skip("Real .frc file not found — skipping")
        return path

    def test_parses_real_file(self, real_frc_path):
        result = parse_frc(real_frc_path)
        params = result["params"]
        assert params["span1"] == 11.2
        assert params["span2"] == 9.2
        assert params["uSecSize"] == "UB_457x152x60"
        assert params["method"] == "parametric"
        assert result["project"]["ProjectName"] == "Sawley Interchange"
